version: "3.4"
services:
  srv:
    image: traefik
    command:
      - "--consul"
      - "--consul.endpoint=consul_srv:8500"
      - "--consul.prefix=traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ingress
      - consul-net
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      labels:
        - traefik.frontend.rule=Host:traefik.anvibo.com
        - traefik.port=8080
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  
networks:
  ingress:
    external: true
  consul-net:
    external: true