version: "3.4"
services:
  srv:
    image: traefik
    command:
            - "traefik"
            - "--api"
            - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
            - "--entrypoints=Name:https Address::443 TLS"
            - "--defaultentrypoints=http,https"
            - "--docker"
            - "--docker.swarmMode"
            - "--docker.domain=anvibo.com"
            - "--docker.watch"
            - "--accesslog"
            - "--acme"
            - "--acme.storage=/etc/traefik/acme/acme.json"
            - "--acme.entryPoint=https"
            - "--acme.httpChallenge.entryPoint=http"
            - "--acme.onHostRule=true"
            - "--acme.onDemand=false"
            - "--acme.email=ssl@anvibo.com"
            - "--acme.acmelogging"
        
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/docker-services/traefik/traefik.toml:/traefik.toml
      - traefik-acme-data:/etc/traefik/acme/
    networks:
      - proxy-net
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == manager
      #restart_policy:
      #  condition: on-failure
      labels:
        - traefik.frontend.rule=Host:proxy.anvibo.com
        - traefik.port=8080

volumes:
        traefik-acme-data:
                external: true
                     
networks:
  proxy-net:
    external: true
  consul-net:
    external: true

