version: "3.4"
services:
  srv:
    image: mariadb
    volumes:
      - /volumes/db1-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db1_root_pwd
    secrets:
        - db1_root_pwd
    networks: 
      - db-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
networks: 
  db-net:
    external: true

secrets:
    db1_root_pwd:
      external: true