version: "3.4"
services:
  srv:
    image: mysql
    volumes:
      - /volumes/db1-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db1_root_pwd

    secrets:
        - db1_root_pwd
    networks: 
      - db-net
    
networks: 
  db-net:
    external: true

secrets:
    db1_root_pwd:
      external: true